apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: product-service-api-migration-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: api-env
              secret:
                secretName: api-env

          containers:
            - name: php
              image: product-service-php
              volumeMounts:
                - name: api-env
                  mountPath: /var/www/html/.env
                  subPath: .env
              args:
                - php
                - artisan
                - migrate
          restartPolicy: OnFailure
